//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hairdresser_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public short Appointment_Id { get; set; }
        public short Appointment_Date_Id { get; set; }
        public System.TimeSpan Appointment_Exact_Time { get; set; }
        public byte Appointment_Service_Id { get; set; }
        public Nullable<bool> Appointment_Reserved { get; set; }
    
        public virtual Dates Dates { get; set; }
        public virtual Services Services { get; set; }
    }
}
