//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hairdresser_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HairdresserEntities : DbContext
    {
        public HairdresserEntities()
            : base("name=HairdresserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Service_Length> Service_Length { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<User_Rank> User_Rank { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
